### ISSUE TITLE
Contao 4.6 Support

### ISSUE THREAD

**Issue by HorstVonMorgen** [srhinow/project-manager-bundle#3]
Hallo, gibt es Aussicht auf die Kompatibiliät mit Version 4.6? Ich habe gerade gemerkt, dass die Installation in Version 4.4 funktioniert, in Version 4.6 aber leider mit Fehler abbricht.
Ich würde mich sehr freuen, wenn diese tolle Erweiterung erhalten bleibt...

**Comment by mr2017x** [comment]
Hallo,

ich kann mich Horst nur anschliessen. Wäre super und danke vorab!

**Comment by srhinow** [comment]
ok dann schau ich mir das die Tage an wo da das Problem ist.

**Comment by srhinow** [comment]
sollte jetzt auch unter Contao 4.6 funktionieren. 

@HorstVonMorgen  @mr2017x Bitte um Feedback
